In [42]:
import pandas as pd
import numpy as np

In [43]:
df = pd.read_csv("Titanic-Dataset.csv")

In [44]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [45]:
df.shape

(891, 12)

In [46]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [47]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [48]:
print(df.isnull().sum());

#we have to print it other wise we get no output

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [49]:
print(df.value_counts())

#again print we have to

PassengerId  Survived  Pclass  Name                                                 Sex     Age   SibSp  Parch  Ticket    Fare     Cabin        Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599  71.2833  C85          C           1
4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803    53.1000  C123         S           1
7            0         1       McCarthy, Mr. Timothy J                              male    54.0  0      0      17463     51.8625  E46          S           1
11           1         3       Sandstrom, Miss. Marguerite Rut                      female  4.0   1      1      PP 9549   16.7000  G6           S           1
12           1         1       Bonnell, Miss. Elizabeth                             female  58.0  0      0      113783    26.5500  C103         S           1
                                                                                                                                                           ..
872          1         1       Beckwith, Mrs. Richard Leonard (Sallie Monypeny)     female  47.0  1      1      11751     52.5542  D35          S           1
873          0         1       Carlsson, Mr. Frans Olof                             male    33.0  0      0      695       5.0000   B51 B53 B55  S           1
880          1         1       Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)        female  56.0  0      1      11767     83.1583  C50          C           1
888          1         1       Graham, Miss. Margaret Edith                         female  19.0  0      0      112053    30.0000  B42          S           1
890          1         1       Behr, Mr. Karl Howell                                male    26.0  0      0      111369    30.0000  C148         C           1
Name: count, Length: 183, dtype: int64

In [50]:
for i in range(1, 5):
  print(df.iloc[i])

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object
PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object
PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object
PassengerId                           5
Survived                              0
Pclass                                3
Name           Allen, Mr. William Henry
Sex                                male
Age                                35.0
SibSp                                 0
Parch                                 0
Ticket                           373450
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 4, dtype: object

In [51]:
#custom questions

print("Q1: did passenger class affect survival rates?")


first = df.loc[df["Pclass"] == 1, "Survived"]
second = df.loc[df["Pclass"] == 2, "Survived"]
third = df.loc[df["Pclass"] == 3, "Survived"]

print("First Class Survival Rate:", first.mean() * 100)
print("Second Class Survival Rate:", second.mean() * 100)
print("hird Class Survival Rate:", third.mean() * 100)


print("/n")




#multiplying with one hundred gives the proper percentage


print("Q2: Which age group had the highest survival rate on the Titanic?")

children = df.loc[df["Age"] < 18, "Survived"]
adults = df.loc[(df["Age"] >= 18) & (df["Age"] < 60), "Survived"]
seniors = df.loc[df["Age"] >= 60, "Survived"]

print("Children Survival Rate:", children.mean() * 100)
print("Adults Survival Rate:", adults.mean() * 100)
print("Seniors Survival Rate:", seniors.mean() * 100)

Q1: did passenger class affect survival rates?
First Class Survival Rate: 62.96296296296296
Second Class Survival Rate: 47.28260869565217
hird Class Survival Rate: 24.236252545824847
/n
Q2: Which age group had the highest survival rate on the Titanic?
Children Survival Rate: 53.98230088495575
Adults Survival Rate: 38.608695652173914
Seniors Survival Rate: 26.923076923076923

In [52]:
#answers

print("Ans Q1:   passengers travelling in first class had a higher survival rate than those travellin in the lower classes")

print("Ans Q2 children had the highest survival rate accrding to the calculations followed by adults and then old people supported by evidence from google")

Ans Q1:   passengers travelling in first class had a higher survival rate than those travellin in the lower classes
Ans Q2 children had the highest survival rate accrding to the calculations followed by adults and then old people supported by evidence from google

In [53]:
#googled evidence


print("""Survival Rates by Demographics

• Children (Overall): Around 51% to 57% survived (varying widely by class).
	• First-class children: ~83% to 86% survived (5 of 6 or 6 of 7).
	• Second-class children: 100% survived (all children saved).
	• Third-class children: About 34% to 42% survived (roughly 27 survived out of 79).
• Adults (Overall): Around 38% of adults survived overall.
	• Women (Adults/Overall): Approximately 74% to 75% survived. First- and second-class women had the highest survival rates (over 85% in second class), while third-class women had a lower rate (under 50%).
	• Men (Adults/Overall): Approximately 20% survived. Men in first class had a slightly higher survival rate than men in second and third classes, though the vast majority perished.
• Old People / Elderly: The survival rate for elderly passengers was extremely low (estimated around 3% or less), as priority for lifeboats was heavily given to women, children, and younger, more mobile passengers.""")

Survival Rates by Demographics

• Children (Overall): Around 51% to 57% survived (varying widely by class).
	• First-class children: ~83% to 86% survived (5 of 6 or 6 of 7).
	• Second-class children: 100% survived (all children saved).
	• Third-class children: About 34% to 42% survived (roughly 27 survived out of 79).
• Adults (Overall): Around 38% of adults survived overall.
	• Women (Adults/Overall): Approximately 74% to 75% survived. First- and second-class women had the highest survival rates (over 85% in second class), while third-class women had a lower rate (under 50%).
	• Men (Adults/Overall): Approximately 20% survived. Men in first class had a slightly higher survival rate than men in second and third classes, though the vast majority perished.
• Old People / Elderly: The survival rate for elderly passengers was extremely low (estimated around 3% or less), as priority for lifeboats was heavily given to women, children, and younger, more mobile passengers.

In [54]:
#completed to the best of my knowledge